version: "2.4"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: America/Chicago
      WEBPASSWORD: ${WEBPASSWORD}
    volumes:
      - '/dockervols/pihole/etc/:/etc/pihole/'
      - '/dockervols/pihole/dnsmasq:/etc/dnsmasq.d/'
      - '/dockervols/pihole/log:/var/log/pihole'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    dns:
      - 127.0.0.1
      - 8.8.8.8

  pihole3:
    container_name: pihole3
    image: pihole/pihole:latest
    environment:
      TZ: America/Chicago
      WEBPASSWORD: ${WEBPASSWORD}
    volumes:
     - './etc-pihole:/etc/pihole'
     - './etc-dnqmasq.d:/etc/dnsmasq.d'
     - './var-log-pihole:/var/log/pihole'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    dns:
      - 127.0.0.1
      - 8.8.8.8
    networks:
      dockervlan:
        ipv4_address: 10.0.0.154

networks:
  dockervlan:
    name: dockervlan
    driver: macvlan
    driver_opts: 
      parent: eth0
    ipam:
      config:
      - subnet: '10.0.0.0/24'
        ip_range: '10.0.0.0/24'
        gateway: '10.0.0.1'
