version: "2.4"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: America/Chicago
      WEBPASSWORD: ${WEBPASSWORD}
    volumes:
      - '/dockervols/pihole/etc/:/etc/pihole/'
      - '/dockervols/pihole/dnsmasq:/etc/dnsmasq.d/'
      - '/dockervols/pihole/log:/var/log/pihole'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    dns:
      - 127.0.0.1
      - 8.8.8.8

  pihole3:
    container_name: pihole3
    image: pihole/pihole:latest
    environment:
      TZ: America/Chicago
      WEBPASSWORD: ${WEBPASSWORD}
    volumes:
     - './pihole3/etc-pihole:/etc/pihole'
     - './pihole3/etc-dnqmasq.d:/etc/dnsmasq.d'
     - './pihole3/var-log-pihole:/var/log/pihole'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    dns:
      - 127.0.0.1
      - 8.8.8.8
    networks:
      trusted:
        ipv4_address: 10.0.0.154

  pihole4:
    container_name: pihole4
    image: pihole/pihole:latest
    environment:
      TZ: America/Chicago
      WEBPASSWORD: ${WEBPASSWORD}
    # Volumes store your data between container upgrades
    volumes:
     - './pihole4/etc-pihole:/etc/pihole'
     - './pihole4/etc-dnqmasq.d:/etc/dnsmasq.d'
     - './pihole4/var-log-pihole:/var/log/pihole'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    dns:
      - 127.0.0.1
      - 8.8.8.8
    networks:
      untrusted:
        ipv4_address: 10.0.1.155

  pihole5:
    container_name: pihole5
    image: pihole/pihole:latest
    environment:
      TZ: America/Chicago
      WEBPASSWORD: ${WEBPASSWORD}
    volumes:
     - './pihole5/etc-pihole:/etc/pihole'
     - './pihole5/etc-dnqmasq.d:/etc/dnsmasq.d'
     - './pihole5/var-log-pihole:/var/log/pihole'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    dns:
      - 127.0.0.1
      - 8.8.8.8
    networks:
      untrusted:
        ipv4_address: 10.0.1.156

  pihole6:
    container_name: pihole6
    image: pihole/pihole:latest
    environment:
      TZ: America/Chicago
      WEBPASSWORD: ${WEBPASSWORD}
    volumes:
     - './pihole6/etc-pihole:/etc/pihole'
     - './pihole6/etc-dnqmasq.d:/etc/dnsmasq.d'
     - './pihole6/var-log-pihole:/var/log/pihole'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    dns:
      - 127.0.0.1
      - 8.8.8.8
    networks:
      work:
        ipv4_address: 10.0.2.155

  pihole7:
    container_name: pihole7
    image: pihole/pihole:latest
    environment:
      TZ: America/Chicago
      WEBPASSWORD: ${WEBPASSWORD}
    volumes:
     - './pihole7/etc-pihole:/etc/pihole'
     - './pihole7/etc-dnqmasq.d:/etc/dnsmasq.d'
     - './pihole7/log:/var/log/pihole'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    dns:
      - 127.0.0.1
      - 8.8.8.8
    networks:
      work:
        ipv4_address: 10.0.2.156

networks:
  trusted:
    name: trusted
    driver: macvlan
    driver_opts: 
      parent: eth0
    ipam:
      config:
      - subnet: '10.0.0.0/24'
        ip_range: '10.0.0.0/24'
        gateway: '10.0.0.1'

  untrusted:
    name: untrusted
    driver: macvlan
    driver_opts: 
      parent: eth0.2
    ipam:
      config:
      - subnet: '10.0.1.0/24'
        ip_range: '10.0.1.0/24'
        gateway: '10.0.1.1'

  work:
    name: work
    driver: macvlan
    driver_opts: 
      parent: eth0.3
    ipam:
      config:
      - subnet: '10.0.2.0/24'
        ip_range: '10.0.2.0/24'
        gateway: '10.0.2.1'        